//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPPremiaProd
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class WSExceptionBean
    {
        
        private thirdPartyCreationFault errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public thirdPartyCreationFault ErrorDetails
        {
            get
            {
                return this.errorDetailsField;
            }
            set
            {
                this.errorDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyCreationFault
    {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyErrorResponseOut
    {
        
        private string err_codeField;
        
        private string err_descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string err_code
        {
            get
            {
                return this.err_codeField;
            }
            set
            {
                this.err_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string err_desc
        {
            get
            {
                return this.err_descField;
            }
            set
            {
                this.err_descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyResponseTpOut
    {
        
        private string tppd_clm_sys_idField;
        
        private string tppd_sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tppd_clm_sys_id
        {
            get
            {
                return this.tppd_clm_sys_idField;
            }
            set
            {
                this.tppd_clm_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tppd_sys_id
        {
            get
            {
                return this.tppd_sys_idField;
            }
            set
            {
                this.tppd_sys_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyCreationResponseInfo
    {
        
        private string p_c_tp_sys_idField;
        
        private string p_c_clm_sys_idField;
        
        private string p_c_error_ynField;
        
        private thirdPartyResponseTpOut[] p_C_CLM_TP_OUTField;
        
        private thirdPartyErrorResponseOut[] p_C_ERROR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string p_c_tp_sys_id
        {
            get
            {
                return this.p_c_tp_sys_idField;
            }
            set
            {
                this.p_c_tp_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string p_c_clm_sys_id
        {
            get
            {
                return this.p_c_clm_sys_idField;
            }
            set
            {
                this.p_c_clm_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string p_c_error_yn
        {
            get
            {
                return this.p_c_error_ynField;
            }
            set
            {
                this.p_c_error_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tpDetailsOut", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public thirdPartyResponseTpOut[] p_C_CLM_TP_OUT
        {
            get
            {
                return this.p_C_CLM_TP_OUTField;
            }
            set
            {
                this.p_C_CLM_TP_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errorDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public thirdPartyErrorResponseOut[] p_C_ERROR_MSG
        {
            get
            {
                return this.p_C_ERROR_MSGField;
            }
            set
            {
                this.p_C_ERROR_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyRequestTpInIn
    {
        
        private string c_tp_sys_idField;
        
        private string c_tp_clm_sys_idField;
        
        private string c_tp_cfd_sys_idField;
        
        private string c_TP_ARABField;
        
        private string c_tp_driver_nameField;
        
        private string c_tp_benf_name_engField;
        
        private string c_tp_benf_name_arabField;
        
        private string c_tp_digitField;
        
        private string c_tp_makeField;
        
        private string c_tp_modelField;
        
        private string c_tp_sequence_noField;
        
        private string c_tp_mobile_noField;
        
        private string c_tp_insurer_nameField;
        
        private string c_tp_more_detailsField;
        
        private string c_tp_benificiary_idField;
        
        private string c_tp_discharge_remarksField;
        
        private string c_tp_mode_of_payField;
        
        private string c_tp_bank_nameField;
        
        private string c_tp_iban_noField;
        
        private string c_TP_PARTY_REF_NOField;
        
        private string c_DOBField;
        
        private string c_tp_flex_01Field;
        
        private string c_tp_flex_02Field;
        
        private string c_tp_flex_03Field;
        
        private string c_tp_flex_04Field;
        
        private string c_tp_flex_05Field;
        
        private string c_tp_flex_06Field;
        
        private string c_tp_flex_07Field;
        
        private string c_tp_flex_08Field;
        
        private string c_tp_flex_09Field;
        
        private string c_tp_flex_10Field;
        
        private string c_tp_flex_11Field;
        
        private string c_tp_flex_12Field;
        
        private string c_tp_flex_13Field;
        
        private string c_tp_flex_14Field;
        
        private string c_tp_flex_15Field;
        
        private string c_tp_flex_16Field;
        
        private string c_tp_flex_17Field;
        
        private string c_tp_flex_18Field;
        
        private string c_tp_flex_19Field;
        
        private string c_tp_flex_20Field;
        
        private string c_tp_flex_21Field;
        
        private string c_tp_flex_22Field;
        
        private string c_tp_flex_23Field;
        
        private string c_tp_flex_24Field;
        
        private string c_tp_flex_25Field;
        
        private string c_tp_flex_26Field;
        
        private string c_tp_flex_27Field;
        
        private string c_tp_flex_28Field;
        
        private string c_tp_flex_29Field;
        
        private string c_tp_flex_30Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string c_tp_sys_id
        {
            get
            {
                return this.c_tp_sys_idField;
            }
            set
            {
                this.c_tp_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string c_tp_clm_sys_id
        {
            get
            {
                return this.c_tp_clm_sys_idField;
            }
            set
            {
                this.c_tp_clm_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string c_tp_cfd_sys_id
        {
            get
            {
                return this.c_tp_cfd_sys_idField;
            }
            set
            {
                this.c_tp_cfd_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string c_TP_ARAB
        {
            get
            {
                return this.c_TP_ARABField;
            }
            set
            {
                this.c_TP_ARABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string c_tp_driver_name
        {
            get
            {
                return this.c_tp_driver_nameField;
            }
            set
            {
                this.c_tp_driver_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string c_tp_benf_name_eng
        {
            get
            {
                return this.c_tp_benf_name_engField;
            }
            set
            {
                this.c_tp_benf_name_engField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string c_tp_benf_name_arab
        {
            get
            {
                return this.c_tp_benf_name_arabField;
            }
            set
            {
                this.c_tp_benf_name_arabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string c_tp_digit
        {
            get
            {
                return this.c_tp_digitField;
            }
            set
            {
                this.c_tp_digitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string c_tp_make
        {
            get
            {
                return this.c_tp_makeField;
            }
            set
            {
                this.c_tp_makeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string c_tp_model
        {
            get
            {
                return this.c_tp_modelField;
            }
            set
            {
                this.c_tp_modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string c_tp_sequence_no
        {
            get
            {
                return this.c_tp_sequence_noField;
            }
            set
            {
                this.c_tp_sequence_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string c_tp_mobile_no
        {
            get
            {
                return this.c_tp_mobile_noField;
            }
            set
            {
                this.c_tp_mobile_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string c_tp_insurer_name
        {
            get
            {
                return this.c_tp_insurer_nameField;
            }
            set
            {
                this.c_tp_insurer_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string c_tp_more_details
        {
            get
            {
                return this.c_tp_more_detailsField;
            }
            set
            {
                this.c_tp_more_detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string c_tp_benificiary_id
        {
            get
            {
                return this.c_tp_benificiary_idField;
            }
            set
            {
                this.c_tp_benificiary_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string c_tp_discharge_remarks
        {
            get
            {
                return this.c_tp_discharge_remarksField;
            }
            set
            {
                this.c_tp_discharge_remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string c_tp_mode_of_pay
        {
            get
            {
                return this.c_tp_mode_of_payField;
            }
            set
            {
                this.c_tp_mode_of_payField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string c_tp_bank_name
        {
            get
            {
                return this.c_tp_bank_nameField;
            }
            set
            {
                this.c_tp_bank_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string c_tp_iban_no
        {
            get
            {
                return this.c_tp_iban_noField;
            }
            set
            {
                this.c_tp_iban_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string c_TP_PARTY_REF_NO
        {
            get
            {
                return this.c_TP_PARTY_REF_NOField;
            }
            set
            {
                this.c_TP_PARTY_REF_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string c_DOB
        {
            get
            {
                return this.c_DOBField;
            }
            set
            {
                this.c_DOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string c_tp_flex_01
        {
            get
            {
                return this.c_tp_flex_01Field;
            }
            set
            {
                this.c_tp_flex_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string c_tp_flex_02
        {
            get
            {
                return this.c_tp_flex_02Field;
            }
            set
            {
                this.c_tp_flex_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string c_tp_flex_03
        {
            get
            {
                return this.c_tp_flex_03Field;
            }
            set
            {
                this.c_tp_flex_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string c_tp_flex_04
        {
            get
            {
                return this.c_tp_flex_04Field;
            }
            set
            {
                this.c_tp_flex_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string c_tp_flex_05
        {
            get
            {
                return this.c_tp_flex_05Field;
            }
            set
            {
                this.c_tp_flex_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string c_tp_flex_06
        {
            get
            {
                return this.c_tp_flex_06Field;
            }
            set
            {
                this.c_tp_flex_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string c_tp_flex_07
        {
            get
            {
                return this.c_tp_flex_07Field;
            }
            set
            {
                this.c_tp_flex_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string c_tp_flex_08
        {
            get
            {
                return this.c_tp_flex_08Field;
            }
            set
            {
                this.c_tp_flex_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string c_tp_flex_09
        {
            get
            {
                return this.c_tp_flex_09Field;
            }
            set
            {
                this.c_tp_flex_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string c_tp_flex_10
        {
            get
            {
                return this.c_tp_flex_10Field;
            }
            set
            {
                this.c_tp_flex_10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string c_tp_flex_11
        {
            get
            {
                return this.c_tp_flex_11Field;
            }
            set
            {
                this.c_tp_flex_11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string c_tp_flex_12
        {
            get
            {
                return this.c_tp_flex_12Field;
            }
            set
            {
                this.c_tp_flex_12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string c_tp_flex_13
        {
            get
            {
                return this.c_tp_flex_13Field;
            }
            set
            {
                this.c_tp_flex_13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string c_tp_flex_14
        {
            get
            {
                return this.c_tp_flex_14Field;
            }
            set
            {
                this.c_tp_flex_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string c_tp_flex_15
        {
            get
            {
                return this.c_tp_flex_15Field;
            }
            set
            {
                this.c_tp_flex_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string c_tp_flex_16
        {
            get
            {
                return this.c_tp_flex_16Field;
            }
            set
            {
                this.c_tp_flex_16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string c_tp_flex_17
        {
            get
            {
                return this.c_tp_flex_17Field;
            }
            set
            {
                this.c_tp_flex_17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string c_tp_flex_18
        {
            get
            {
                return this.c_tp_flex_18Field;
            }
            set
            {
                this.c_tp_flex_18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string c_tp_flex_19
        {
            get
            {
                return this.c_tp_flex_19Field;
            }
            set
            {
                this.c_tp_flex_19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string c_tp_flex_20
        {
            get
            {
                return this.c_tp_flex_20Field;
            }
            set
            {
                this.c_tp_flex_20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string c_tp_flex_21
        {
            get
            {
                return this.c_tp_flex_21Field;
            }
            set
            {
                this.c_tp_flex_21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string c_tp_flex_22
        {
            get
            {
                return this.c_tp_flex_22Field;
            }
            set
            {
                this.c_tp_flex_22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string c_tp_flex_23
        {
            get
            {
                return this.c_tp_flex_23Field;
            }
            set
            {
                this.c_tp_flex_23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string c_tp_flex_24
        {
            get
            {
                return this.c_tp_flex_24Field;
            }
            set
            {
                this.c_tp_flex_24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string c_tp_flex_25
        {
            get
            {
                return this.c_tp_flex_25Field;
            }
            set
            {
                this.c_tp_flex_25Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string c_tp_flex_26
        {
            get
            {
                return this.c_tp_flex_26Field;
            }
            set
            {
                this.c_tp_flex_26Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string c_tp_flex_27
        {
            get
            {
                return this.c_tp_flex_27Field;
            }
            set
            {
                this.c_tp_flex_27Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string c_tp_flex_28
        {
            get
            {
                return this.c_tp_flex_28Field;
            }
            set
            {
                this.c_tp_flex_28Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string c_tp_flex_29
        {
            get
            {
                return this.c_tp_flex_29Field;
            }
            set
            {
                this.c_tp_flex_29Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string c_tp_flex_30
        {
            get
            {
                return this.c_tp_flex_30Field;
            }
            set
            {
                this.c_tp_flex_30Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/")]
    public partial class thirdPartyCreationRequestInfo
    {
        
        private string p_c_tp_tran_sys_idField;
        
        private string p_c_tp_insert_update_flagField;
        
        private string p_c_claim_sys_idField;
        
        private thirdPartyRequestTpInIn[] p_c_clm_tp_inField;
        
        private string p_c_tp_flexi_01Field;
        
        private string p_c_tp_flexi_02Field;
        
        private string p_c_tp_flexi_03Field;
        
        private string p_c_tp_flexi_04Field;
        
        private string p_c_tp_flexi_05Field;
        
        private string p_c_tp_flexi_06Field;
        
        private string p_c_tp_flexi_07Field;
        
        private string p_c_tp_flexi_08Field;
        
        private string p_c_tp_flexi_09Field;
        
        private string p_c_tp_flexi_10Field;
        
        private string p_c_tp_flexi_11Field;
        
        private string p_c_tp_flexi_12Field;
        
        private string p_c_tp_flexi_13Field;
        
        private string p_c_tp_flexi_14Field;
        
        private string p_c_tp_flexi_15Field;
        
        private string p_c_tp_flexi_16Field;
        
        private string p_c_tp_flexi_17Field;
        
        private string p_c_tp_flexi_18Field;
        
        private string p_c_tp_flexi_19Field;
        
        private string p_c_tp_flexi_20Field;
        
        private string p_c_tp_flexi_21Field;
        
        private string p_c_tp_flexi_22Field;
        
        private string p_c_tp_flexi_23Field;
        
        private string p_c_tp_flexi_24Field;
        
        private string p_c_tp_flexi_25Field;
        
        private string p_c_tp_flexi_26Field;
        
        private string p_c_tp_flexi_27Field;
        
        private string p_c_tp_flexi_28Field;
        
        private string p_c_tp_flexi_29Field;
        
        private string p_c_tp_flexi_30Field;
        
        private string p_c_tp_flexi_31Field;
        
        private string p_c_tp_flexi_32Field;
        
        private string p_c_tp_flexi_33Field;
        
        private string p_c_tp_flexi_34Field;
        
        private string p_c_tp_flexi_35Field;
        
        private string p_c_tp_flexi_36Field;
        
        private string p_c_tp_flexi_37Field;
        
        private string p_c_tp_flexi_38Field;
        
        private string p_c_tp_flexi_39Field;
        
        private string p_c_tp_flexi_40Field;
        
        private string p_c_tp_flexi_41Field;
        
        private string p_c_tp_flexi_42Field;
        
        private string p_c_tp_flexi_43Field;
        
        private string p_c_tp_flexi_44Field;
        
        private string p_c_tp_flexi_45Field;
        
        private string p_c_tp_flexi_46Field;
        
        private string p_c_tp_flexi_47Field;
        
        private string p_c_tp_flexi_48Field;
        
        private string p_c_tp_flexi_49Field;
        
        private string p_c_tp_flexi_50Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string p_c_tp_tran_sys_id
        {
            get
            {
                return this.p_c_tp_tran_sys_idField;
            }
            set
            {
                this.p_c_tp_tran_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string p_c_tp_insert_update_flag
        {
            get
            {
                return this.p_c_tp_insert_update_flagField;
            }
            set
            {
                this.p_c_tp_insert_update_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string p_c_claim_sys_id
        {
            get
            {
                return this.p_c_claim_sys_idField;
            }
            set
            {
                this.p_c_claim_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tpDetailsIn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public thirdPartyRequestTpInIn[] p_c_clm_tp_in
        {
            get
            {
                return this.p_c_clm_tp_inField;
            }
            set
            {
                this.p_c_clm_tp_inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string p_c_tp_flexi_01
        {
            get
            {
                return this.p_c_tp_flexi_01Field;
            }
            set
            {
                this.p_c_tp_flexi_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string p_c_tp_flexi_02
        {
            get
            {
                return this.p_c_tp_flexi_02Field;
            }
            set
            {
                this.p_c_tp_flexi_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string p_c_tp_flexi_03
        {
            get
            {
                return this.p_c_tp_flexi_03Field;
            }
            set
            {
                this.p_c_tp_flexi_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string p_c_tp_flexi_04
        {
            get
            {
                return this.p_c_tp_flexi_04Field;
            }
            set
            {
                this.p_c_tp_flexi_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string p_c_tp_flexi_05
        {
            get
            {
                return this.p_c_tp_flexi_05Field;
            }
            set
            {
                this.p_c_tp_flexi_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string p_c_tp_flexi_06
        {
            get
            {
                return this.p_c_tp_flexi_06Field;
            }
            set
            {
                this.p_c_tp_flexi_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string p_c_tp_flexi_07
        {
            get
            {
                return this.p_c_tp_flexi_07Field;
            }
            set
            {
                this.p_c_tp_flexi_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string p_c_tp_flexi_08
        {
            get
            {
                return this.p_c_tp_flexi_08Field;
            }
            set
            {
                this.p_c_tp_flexi_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string p_c_tp_flexi_09
        {
            get
            {
                return this.p_c_tp_flexi_09Field;
            }
            set
            {
                this.p_c_tp_flexi_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string p_c_tp_flexi_10
        {
            get
            {
                return this.p_c_tp_flexi_10Field;
            }
            set
            {
                this.p_c_tp_flexi_10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string p_c_tp_flexi_11
        {
            get
            {
                return this.p_c_tp_flexi_11Field;
            }
            set
            {
                this.p_c_tp_flexi_11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string p_c_tp_flexi_12
        {
            get
            {
                return this.p_c_tp_flexi_12Field;
            }
            set
            {
                this.p_c_tp_flexi_12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string p_c_tp_flexi_13
        {
            get
            {
                return this.p_c_tp_flexi_13Field;
            }
            set
            {
                this.p_c_tp_flexi_13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string p_c_tp_flexi_14
        {
            get
            {
                return this.p_c_tp_flexi_14Field;
            }
            set
            {
                this.p_c_tp_flexi_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string p_c_tp_flexi_15
        {
            get
            {
                return this.p_c_tp_flexi_15Field;
            }
            set
            {
                this.p_c_tp_flexi_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string p_c_tp_flexi_16
        {
            get
            {
                return this.p_c_tp_flexi_16Field;
            }
            set
            {
                this.p_c_tp_flexi_16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string p_c_tp_flexi_17
        {
            get
            {
                return this.p_c_tp_flexi_17Field;
            }
            set
            {
                this.p_c_tp_flexi_17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string p_c_tp_flexi_18
        {
            get
            {
                return this.p_c_tp_flexi_18Field;
            }
            set
            {
                this.p_c_tp_flexi_18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string p_c_tp_flexi_19
        {
            get
            {
                return this.p_c_tp_flexi_19Field;
            }
            set
            {
                this.p_c_tp_flexi_19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string p_c_tp_flexi_20
        {
            get
            {
                return this.p_c_tp_flexi_20Field;
            }
            set
            {
                this.p_c_tp_flexi_20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string p_c_tp_flexi_21
        {
            get
            {
                return this.p_c_tp_flexi_21Field;
            }
            set
            {
                this.p_c_tp_flexi_21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string p_c_tp_flexi_22
        {
            get
            {
                return this.p_c_tp_flexi_22Field;
            }
            set
            {
                this.p_c_tp_flexi_22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string p_c_tp_flexi_23
        {
            get
            {
                return this.p_c_tp_flexi_23Field;
            }
            set
            {
                this.p_c_tp_flexi_23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string p_c_tp_flexi_24
        {
            get
            {
                return this.p_c_tp_flexi_24Field;
            }
            set
            {
                this.p_c_tp_flexi_24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string p_c_tp_flexi_25
        {
            get
            {
                return this.p_c_tp_flexi_25Field;
            }
            set
            {
                this.p_c_tp_flexi_25Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string p_c_tp_flexi_26
        {
            get
            {
                return this.p_c_tp_flexi_26Field;
            }
            set
            {
                this.p_c_tp_flexi_26Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string p_c_tp_flexi_27
        {
            get
            {
                return this.p_c_tp_flexi_27Field;
            }
            set
            {
                this.p_c_tp_flexi_27Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string p_c_tp_flexi_28
        {
            get
            {
                return this.p_c_tp_flexi_28Field;
            }
            set
            {
                this.p_c_tp_flexi_28Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string p_c_tp_flexi_29
        {
            get
            {
                return this.p_c_tp_flexi_29Field;
            }
            set
            {
                this.p_c_tp_flexi_29Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string p_c_tp_flexi_30
        {
            get
            {
                return this.p_c_tp_flexi_30Field;
            }
            set
            {
                this.p_c_tp_flexi_30Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string p_c_tp_flexi_31
        {
            get
            {
                return this.p_c_tp_flexi_31Field;
            }
            set
            {
                this.p_c_tp_flexi_31Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string p_c_tp_flexi_32
        {
            get
            {
                return this.p_c_tp_flexi_32Field;
            }
            set
            {
                this.p_c_tp_flexi_32Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string p_c_tp_flexi_33
        {
            get
            {
                return this.p_c_tp_flexi_33Field;
            }
            set
            {
                this.p_c_tp_flexi_33Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string p_c_tp_flexi_34
        {
            get
            {
                return this.p_c_tp_flexi_34Field;
            }
            set
            {
                this.p_c_tp_flexi_34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string p_c_tp_flexi_35
        {
            get
            {
                return this.p_c_tp_flexi_35Field;
            }
            set
            {
                this.p_c_tp_flexi_35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string p_c_tp_flexi_36
        {
            get
            {
                return this.p_c_tp_flexi_36Field;
            }
            set
            {
                this.p_c_tp_flexi_36Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string p_c_tp_flexi_37
        {
            get
            {
                return this.p_c_tp_flexi_37Field;
            }
            set
            {
                this.p_c_tp_flexi_37Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string p_c_tp_flexi_38
        {
            get
            {
                return this.p_c_tp_flexi_38Field;
            }
            set
            {
                this.p_c_tp_flexi_38Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string p_c_tp_flexi_39
        {
            get
            {
                return this.p_c_tp_flexi_39Field;
            }
            set
            {
                this.p_c_tp_flexi_39Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string p_c_tp_flexi_40
        {
            get
            {
                return this.p_c_tp_flexi_40Field;
            }
            set
            {
                this.p_c_tp_flexi_40Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string p_c_tp_flexi_41
        {
            get
            {
                return this.p_c_tp_flexi_41Field;
            }
            set
            {
                this.p_c_tp_flexi_41Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string p_c_tp_flexi_42
        {
            get
            {
                return this.p_c_tp_flexi_42Field;
            }
            set
            {
                this.p_c_tp_flexi_42Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string p_c_tp_flexi_43
        {
            get
            {
                return this.p_c_tp_flexi_43Field;
            }
            set
            {
                this.p_c_tp_flexi_43Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string p_c_tp_flexi_44
        {
            get
            {
                return this.p_c_tp_flexi_44Field;
            }
            set
            {
                this.p_c_tp_flexi_44Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string p_c_tp_flexi_45
        {
            get
            {
                return this.p_c_tp_flexi_45Field;
            }
            set
            {
                this.p_c_tp_flexi_45Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string p_c_tp_flexi_46
        {
            get
            {
                return this.p_c_tp_flexi_46Field;
            }
            set
            {
                this.p_c_tp_flexi_46Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string p_c_tp_flexi_47
        {
            get
            {
                return this.p_c_tp_flexi_47Field;
            }
            set
            {
                this.p_c_tp_flexi_47Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string p_c_tp_flexi_48
        {
            get
            {
                return this.p_c_tp_flexi_48Field;
            }
            set
            {
                this.p_c_tp_flexi_48Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string p_c_tp_flexi_49
        {
            get
            {
                return this.p_c_tp_flexi_49Field;
            }
            set
            {
                this.p_c_tp_flexi_49Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string p_c_tp_flexi_50
        {
            get
            {
                return this.p_c_tp_flexi_50Field;
            }
            set
            {
                this.p_c_tp_flexi_50Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thirdparty.services.insurance.arabia.com/", ConfigurationName="TPPremiaProd.ThirdPartyCreationRequestService")]
    public interface ThirdPartyCreationRequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TPPremiaProd.WSExceptionBean), Action="", Name="WSScheduleFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TPPremiaProd.ThirdPartyCreationServiceResponse ThirdPartyCreationService(TPPremiaProd.ThirdPartyCreationService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TPPremiaProd.ThirdPartyCreationServiceResponse> ThirdPartyCreationServiceAsync(TPPremiaProd.ThirdPartyCreationService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThirdPartyCreationService", WrapperNamespace="http://thirdparty.services.insurance.arabia.com/", IsWrapped=true)]
    public partial class ThirdPartyCreationService
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TPPremiaProd.thirdPartyCreationRequestInfo ThirdPartyCreationRequestInfo;
        
        public ThirdPartyCreationService()
        {
        }
        
        public ThirdPartyCreationService(TPPremiaProd.thirdPartyCreationRequestInfo ThirdPartyCreationRequestInfo)
        {
            this.ThirdPartyCreationRequestInfo = ThirdPartyCreationRequestInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ThirdPartyCreationServiceResponse", WrapperNamespace="http://thirdparty.services.insurance.arabia.com/", IsWrapped=true)]
    public partial class ThirdPartyCreationServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TPPremiaProd.thirdPartyCreationResponseInfo ThirdPartyCreationResponse;
        
        public ThirdPartyCreationServiceResponse()
        {
        }
        
        public ThirdPartyCreationServiceResponse(TPPremiaProd.thirdPartyCreationResponseInfo ThirdPartyCreationResponse)
        {
            this.ThirdPartyCreationResponse = ThirdPartyCreationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ThirdPartyCreationRequestServiceChannel : TPPremiaProd.ThirdPartyCreationRequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ThirdPartyCreationRequestServiceClient : System.ServiceModel.ClientBase<TPPremiaProd.ThirdPartyCreationRequestService>, TPPremiaProd.ThirdPartyCreationRequestService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ThirdPartyCreationRequestServiceClient() : 
                base(ThirdPartyCreationRequestServiceClient.GetDefaultBinding(), ThirdPartyCreationRequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ThirdPartyCreationRequestServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThirdPartyCreationRequestServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ThirdPartyCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), ThirdPartyCreationRequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThirdPartyCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ThirdPartyCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThirdPartyCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ThirdPartyCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThirdPartyCreationRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TPPremiaProd.ThirdPartyCreationServiceResponse ThirdPartyCreationService(TPPremiaProd.ThirdPartyCreationService request)
        {
            return base.Channel.ThirdPartyCreationService(request);
        }
        
        public System.Threading.Tasks.Task<TPPremiaProd.ThirdPartyCreationServiceResponse> ThirdPartyCreationServiceAsync(TPPremiaProd.ThirdPartyCreationService request)
        {
            return base.Channel.ThirdPartyCreationServiceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ThirdPartyCreationRequestServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ThirdPartyCreationRequestServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ArabiaPolicyClaimWebService/ThirdPartyCreationRequestServic" +
                        "e");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ThirdPartyCreationRequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.ThirdPartyCreationRequestServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ThirdPartyCreationRequestServiceClient.GetEndpointAddress(EndpointConfiguration.ThirdPartyCreationRequestServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ThirdPartyCreationRequestServicePort,
        }
    }
}
