//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiaEstimationProd
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class WSExceptionBean
    {
        
        private estimateCreationFault errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estimateCreationFault ErrorDetails
        {
            get
            {
                return this.errorDetailsField;
            }
            set
            {
                this.errorDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class estimateCreationFault
    {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class estimateErrorResponseOut
    {
        
        private string eRR_CODEField;
        
        private string eRR_DESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ERR_CODE
        {
            get
            {
                return this.eRR_CODEField;
            }
            set
            {
                this.eRR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ERR_DESC
        {
            get
            {
                return this.eRR_DESCField;
            }
            set
            {
                this.eRR_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class estimateClampDetailsOut
    {
        
        private string cE_CLM_SYS_IDField;
        
        private string cE_CLMAP_SYS_IDField;
        
        private string cE_SYS_IDField;
        
        private string cE_PARTY_REF_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CE_CLM_SYS_ID
        {
            get
            {
                return this.cE_CLM_SYS_IDField;
            }
            set
            {
                this.cE_CLM_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CE_CLMAP_SYS_ID
        {
            get
            {
                return this.cE_CLMAP_SYS_IDField;
            }
            set
            {
                this.cE_CLMAP_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CE_SYS_ID
        {
            get
            {
                return this.cE_SYS_IDField;
            }
            set
            {
                this.cE_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CE_PARTY_REF_NO
        {
            get
            {
                return this.cE_PARTY_REF_NOField;
            }
            set
            {
                this.cE_PARTY_REF_NOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class estimateCreationResponseInfo
    {
        
        private estimateClampDetailsOut[] p_C_EST_DTLS_OUTField;
        
        private string p_C_ERROR_YNField;
        
        private estimateErrorResponseOut[] p_C_ERROR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("clampDetailsOut", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public estimateClampDetailsOut[] p_C_EST_DTLS_OUT
        {
            get
            {
                return this.p_C_EST_DTLS_OUTField;
            }
            set
            {
                this.p_C_EST_DTLS_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string p_C_ERROR_YN
        {
            get
            {
                return this.p_C_ERROR_YNField;
            }
            set
            {
                this.p_C_ERROR_YNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ErrorDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public estimateErrorResponseOut[] p_C_ERROR_MSG
        {
            get
            {
                return this.p_C_ERROR_MSGField;
            }
            set
            {
                this.p_C_ERROR_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class claimEstimateDtls
    {
        
        private string c_EST_CLMAP_SYS_IDField;
        
        private string c_EST_SYS_IDField;
        
        private string c_EST_PROVISION_DTField;
        
        private string c_EST_CODEField;
        
        private string c_EST_CUSTOMER_CODEField;
        
        private string c_EST_CURR_CODEField;
        
        private string c_EST_PROVISION_AMTField;
        
        private string c_EST_PARTY_REF_NOField;
        
        private string c_EST_APPR_YNField;
        
        private string c_EST_CLOSE_YNField;
        
        private string c_EST_PARA_1Field;
        
        private string c_EST_PARA_2Field;
        
        private string c_EST_PARA_3Field;
        
        private string c_EST_PARA_4Field;
        
        private string c_EST_PARA_5Field;
        
        private string c_EST_PARA_6Field;
        
        private string c_EST_PARA_7Field;
        
        private string c_EST_PARA_8Field;
        
        private string c_EST_PARA_9Field;
        
        private string c_EST_PARA_10Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string c_EST_CLMAP_SYS_ID
        {
            get
            {
                return this.c_EST_CLMAP_SYS_IDField;
            }
            set
            {
                this.c_EST_CLMAP_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string c_EST_SYS_ID
        {
            get
            {
                return this.c_EST_SYS_IDField;
            }
            set
            {
                this.c_EST_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string c_EST_PROVISION_DT
        {
            get
            {
                return this.c_EST_PROVISION_DTField;
            }
            set
            {
                this.c_EST_PROVISION_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string c_EST_CODE
        {
            get
            {
                return this.c_EST_CODEField;
            }
            set
            {
                this.c_EST_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string c_EST_CUSTOMER_CODE
        {
            get
            {
                return this.c_EST_CUSTOMER_CODEField;
            }
            set
            {
                this.c_EST_CUSTOMER_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string c_EST_CURR_CODE
        {
            get
            {
                return this.c_EST_CURR_CODEField;
            }
            set
            {
                this.c_EST_CURR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string c_EST_PROVISION_AMT
        {
            get
            {
                return this.c_EST_PROVISION_AMTField;
            }
            set
            {
                this.c_EST_PROVISION_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string c_EST_PARTY_REF_NO
        {
            get
            {
                return this.c_EST_PARTY_REF_NOField;
            }
            set
            {
                this.c_EST_PARTY_REF_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string c_EST_APPR_YN
        {
            get
            {
                return this.c_EST_APPR_YNField;
            }
            set
            {
                this.c_EST_APPR_YNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string c_EST_CLOSE_YN
        {
            get
            {
                return this.c_EST_CLOSE_YNField;
            }
            set
            {
                this.c_EST_CLOSE_YNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string c_EST_PARA_1
        {
            get
            {
                return this.c_EST_PARA_1Field;
            }
            set
            {
                this.c_EST_PARA_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string c_EST_PARA_2
        {
            get
            {
                return this.c_EST_PARA_2Field;
            }
            set
            {
                this.c_EST_PARA_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string c_EST_PARA_3
        {
            get
            {
                return this.c_EST_PARA_3Field;
            }
            set
            {
                this.c_EST_PARA_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string c_EST_PARA_4
        {
            get
            {
                return this.c_EST_PARA_4Field;
            }
            set
            {
                this.c_EST_PARA_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string c_EST_PARA_5
        {
            get
            {
                return this.c_EST_PARA_5Field;
            }
            set
            {
                this.c_EST_PARA_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string c_EST_PARA_6
        {
            get
            {
                return this.c_EST_PARA_6Field;
            }
            set
            {
                this.c_EST_PARA_6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string c_EST_PARA_7
        {
            get
            {
                return this.c_EST_PARA_7Field;
            }
            set
            {
                this.c_EST_PARA_7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string c_EST_PARA_8
        {
            get
            {
                return this.c_EST_PARA_8Field;
            }
            set
            {
                this.c_EST_PARA_8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string c_EST_PARA_9
        {
            get
            {
                return this.c_EST_PARA_9Field;
            }
            set
            {
                this.c_EST_PARA_9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string c_EST_PARA_10
        {
            get
            {
                return this.c_EST_PARA_10Field;
            }
            set
            {
                this.c_EST_PARA_10Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/")]
    public partial class estimateCreationRequestInfo
    {
        
        private string p_C_EST_TRAN_SYS_IDField;
        
        private string p_C_EST_INSERT_UPDATE_FLAGField;
        
        private string p_C_EST_CLM_SYS_IDField;
        
        private claimEstimateDtls[] p_C_EST_DTLS_INField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string p_C_EST_TRAN_SYS_ID
        {
            get
            {
                return this.p_C_EST_TRAN_SYS_IDField;
            }
            set
            {
                this.p_C_EST_TRAN_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string p_C_EST_INSERT_UPDATE_FLAG
        {
            get
            {
                return this.p_C_EST_INSERT_UPDATE_FLAGField;
            }
            set
            {
                this.p_C_EST_INSERT_UPDATE_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string p_C_EST_CLM_SYS_ID
        {
            get
            {
                return this.p_C_EST_CLM_SYS_IDField;
            }
            set
            {
                this.p_C_EST_CLM_SYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public claimEstimateDtls[] p_C_EST_DTLS_IN
        {
            get
            {
                return this.p_C_EST_DTLS_INField;
            }
            set
            {
                this.p_C_EST_DTLS_INField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://estimate.service.claim.policy.arabia.com/", ConfigurationName="PremiaEstimationProd.EstimateCreationRequestService")]
    public interface EstimateCreationRequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PremiaEstimationProd.WSExceptionBean), Action="", Name="WSScheduleFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PremiaEstimationProd.EstimateCreationServiceResponse EstimateCreationService(PremiaEstimationProd.EstimateCreationService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PremiaEstimationProd.EstimateCreationServiceResponse> EstimateCreationServiceAsync(PremiaEstimationProd.EstimateCreationService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstimateCreationService", WrapperNamespace="http://estimate.service.claim.policy.arabia.com/", IsWrapped=true)]
    public partial class EstimateCreationService
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public PremiaEstimationProd.estimateCreationRequestInfo EstimateCreationRequestInfo;
        
        public EstimateCreationService()
        {
        }
        
        public EstimateCreationService(PremiaEstimationProd.estimateCreationRequestInfo EstimateCreationRequestInfo)
        {
            this.EstimateCreationRequestInfo = EstimateCreationRequestInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstimateCreationServiceResponse", WrapperNamespace="http://estimate.service.claim.policy.arabia.com/", IsWrapped=true)]
    public partial class EstimateCreationServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public PremiaEstimationProd.estimateCreationResponseInfo EstimateCreationService;
        
        public EstimateCreationServiceResponse()
        {
        }
        
        public EstimateCreationServiceResponse(PremiaEstimationProd.estimateCreationResponseInfo EstimateCreationService)
        {
            this.EstimateCreationService = EstimateCreationService;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EstimateCreationRequestServiceChannel : PremiaEstimationProd.EstimateCreationRequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EstimateCreationRequestServiceClient : System.ServiceModel.ClientBase<PremiaEstimationProd.EstimateCreationRequestService>, PremiaEstimationProd.EstimateCreationRequestService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstimateCreationRequestServiceClient() : 
                base(EstimateCreationRequestServiceClient.GetDefaultBinding(), EstimateCreationRequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EstimateCreationRequestServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstimateCreationRequestServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EstimateCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), EstimateCreationRequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstimateCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstimateCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstimateCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstimateCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstimateCreationRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PremiaEstimationProd.EstimateCreationServiceResponse EstimateCreationService(PremiaEstimationProd.EstimateCreationService request)
        {
            return base.Channel.EstimateCreationService(request);
        }
        
        public System.Threading.Tasks.Task<PremiaEstimationProd.EstimateCreationServiceResponse> EstimateCreationServiceAsync(PremiaEstimationProd.EstimateCreationService request)
        {
            return base.Channel.EstimateCreationServiceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EstimateCreationRequestServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EstimateCreationRequestServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ArabiaPolicyClaimWebService/EstimateCreationRequestService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EstimateCreationRequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.EstimateCreationRequestServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EstimateCreationRequestServiceClient.GetEndpointAddress(EndpointConfiguration.EstimateCreationRequestServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            EstimateCreationRequestServicePort,
        }
    }
}
