//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiaSettlmentProd
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class WSExceptionBean
    {
        
        private settlementCreationFault errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public settlementCreationFault ErrorDetails
        {
            get
            {
                return this.errorDetailsField;
            }
            set
            {
                this.errorDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementCreationFault
    {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class vatOutResponseOut
    {
        
        private string vat_descField;
        
        private string vat_percField;
        
        private string vat_amtField;
        
        private string vat_inv_ynField;
        
        private string vat_amod_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vat_desc
        {
            get
            {
                return this.vat_descField;
            }
            set
            {
                this.vat_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vat_perc
        {
            get
            {
                return this.vat_percField;
            }
            set
            {
                this.vat_percField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vat_amt
        {
            get
            {
                return this.vat_amtField;
            }
            set
            {
                this.vat_amtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vat_inv_yn
        {
            get
            {
                return this.vat_inv_ynField;
            }
            set
            {
                this.vat_inv_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vat_amod_yn
        {
            get
            {
                return this.vat_amod_ynField;
            }
            set
            {
                this.vat_amod_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementResponseOut
    {
        
        private string cs_sys_idField;
        
        private string cs_clm_sys_idField;
        
        private string cs_ce_sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cs_sys_id
        {
            get
            {
                return this.cs_sys_idField;
            }
            set
            {
                this.cs_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cs_clm_sys_id
        {
            get
            {
                return this.cs_clm_sys_idField;
            }
            set
            {
                this.cs_clm_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cs_ce_sys_id
        {
            get
            {
                return this.cs_ce_sys_idField;
            }
            set
            {
                this.cs_ce_sys_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementErrorResponseOut
    {
        
        private string eRR_CODEField;
        
        private string eRR_DESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ERR_CODE
        {
            get
            {
                return this.eRR_CODEField;
            }
            set
            {
                this.eRR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ERR_DESC
        {
            get
            {
                return this.eRR_DESCField;
            }
            set
            {
                this.eRR_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementCreationResponseInfo
    {
        
        private string p_c_errro_ynField;
        
        private settlementErrorResponseOut[] p_c_error_msgField;
        
        private settlementResponseOut[] c_clm_setl_outField;
        
        private vatOutResponseOut[] p_c_vat_outField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string p_c_errro_yn
        {
            get
            {
                return this.p_c_errro_ynField;
            }
            set
            {
                this.p_c_errro_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ErrorDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public settlementErrorResponseOut[] p_c_error_msg
        {
            get
            {
                return this.p_c_error_msgField;
            }
            set
            {
                this.p_c_error_msgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("settlementresponseoutinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public settlementResponseOut[] c_clm_setl_out
        {
            get
            {
                return this.c_clm_setl_outField;
            }
            set
            {
                this.c_clm_setl_outField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public vatOutResponseOut[] p_c_vat_out
        {
            get
            {
                return this.p_c_vat_outField;
            }
            set
            {
                this.p_c_vat_outField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementRequestIn
    {
        
        private string c_setl_ce_sys_idField;
        
        private string c_setl_cs_sys_idField;
        
        private string c_setl_est_codeField;
        
        private string c_setl_dateField;
        
        private string c_setl_amtField;
        
        private string c_setl_cust_codeField;
        
        private string c_setl_payee_codeField;
        
        private string c_setl_remarksField;
        
        private string c_setl_cust_nameField;
        
        private string c_setl_ynField;
        
        private string c_setl_final_ynField;
        
        private string c_setl_mode_of_paymentField;
        
        private string c_setl_iban_noField;
        
        private string c_setl_benf_idField;
        
        private string c_setl_bank_nameField;
        
        private string c_setl_benf_name_engField;
        
        private string c_setl_benf_name_arabField;
        
        private string c_setl_transfer_of_owner_ynField;
        
        private string c_setl_date_of_trans_ownerField;
        
        private string c_setl_veh_reg_recv_ynField;
        
        private string c_setl_veh_statusField;
        
        private string c_setl_date_of_veh_regField;
        
        private string c_setl_keys_recvField;
        
        private string c_setl_salvage_recv_ynField;
        
        private string c_setl_salvage_stsField;
        
        private string c_setl_traffic_dept_ynField;
        
        private string c_setl_clmap_sys_id_inField;
        
        private string c_setl_flex_01Field;
        
        private string c_setl_flex_02Field;
        
        private string c_setl_flex_03Field;
        
        private string c_setl_flex_04Field;
        
        private string c_setl_flex_05Field;
        
        private string c_setl_flex_06Field;
        
        private string c_setl_flex_07Field;
        
        private string c_setl_flex_08Field;
        
        private string c_setl_flex_09Field;
        
        private string c_setl_flex_10Field;
        
        private string c_setl_flex_11Field;
        
        private string c_setl_flex_12Field;
        
        private string c_setl_flex_13Field;
        
        private string c_setl_flex_14Field;
        
        private string c_setl_flex_15Field;
        
        private string c_setl_flex_16Field;
        
        private string c_setl_flex_17Field;
        
        private string c_setl_flex_18Field;
        
        private string c_setl_flex_19Field;
        
        private string c_setl_flex_20Field;
        
        private string c_setl_flex_21Field;
        
        private string c_setl_flex_22Field;
        
        private string c_setl_flex_23Field;
        
        private string c_setl_flex_24Field;
        
        private string c_setl_flex_25Field;
        
        private string c_setl_flex_26Field;
        
        private string c_setl_flex_27Field;
        
        private string c_setl_flex_28Field;
        
        private string c_setl_flex_29Field;
        
        private string c_setl_flex_30Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string c_setl_ce_sys_id
        {
            get
            {
                return this.c_setl_ce_sys_idField;
            }
            set
            {
                this.c_setl_ce_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string c_setl_cs_sys_id
        {
            get
            {
                return this.c_setl_cs_sys_idField;
            }
            set
            {
                this.c_setl_cs_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string c_setl_est_code
        {
            get
            {
                return this.c_setl_est_codeField;
            }
            set
            {
                this.c_setl_est_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string c_setl_date
        {
            get
            {
                return this.c_setl_dateField;
            }
            set
            {
                this.c_setl_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string c_setl_amt
        {
            get
            {
                return this.c_setl_amtField;
            }
            set
            {
                this.c_setl_amtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string c_setl_cust_code
        {
            get
            {
                return this.c_setl_cust_codeField;
            }
            set
            {
                this.c_setl_cust_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string c_setl_payee_code
        {
            get
            {
                return this.c_setl_payee_codeField;
            }
            set
            {
                this.c_setl_payee_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string c_setl_remarks
        {
            get
            {
                return this.c_setl_remarksField;
            }
            set
            {
                this.c_setl_remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string c_setl_cust_name
        {
            get
            {
                return this.c_setl_cust_nameField;
            }
            set
            {
                this.c_setl_cust_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string c_setl_yn
        {
            get
            {
                return this.c_setl_ynField;
            }
            set
            {
                this.c_setl_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string c_setl_final_yn
        {
            get
            {
                return this.c_setl_final_ynField;
            }
            set
            {
                this.c_setl_final_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string c_setl_mode_of_payment
        {
            get
            {
                return this.c_setl_mode_of_paymentField;
            }
            set
            {
                this.c_setl_mode_of_paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string c_setl_iban_no
        {
            get
            {
                return this.c_setl_iban_noField;
            }
            set
            {
                this.c_setl_iban_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string c_setl_benf_id
        {
            get
            {
                return this.c_setl_benf_idField;
            }
            set
            {
                this.c_setl_benf_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string c_setl_bank_name
        {
            get
            {
                return this.c_setl_bank_nameField;
            }
            set
            {
                this.c_setl_bank_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string c_setl_benf_name_eng
        {
            get
            {
                return this.c_setl_benf_name_engField;
            }
            set
            {
                this.c_setl_benf_name_engField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string c_setl_benf_name_arab
        {
            get
            {
                return this.c_setl_benf_name_arabField;
            }
            set
            {
                this.c_setl_benf_name_arabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string c_setl_transfer_of_owner_yn
        {
            get
            {
                return this.c_setl_transfer_of_owner_ynField;
            }
            set
            {
                this.c_setl_transfer_of_owner_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string c_setl_date_of_trans_owner
        {
            get
            {
                return this.c_setl_date_of_trans_ownerField;
            }
            set
            {
                this.c_setl_date_of_trans_ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string c_setl_veh_reg_recv_yn
        {
            get
            {
                return this.c_setl_veh_reg_recv_ynField;
            }
            set
            {
                this.c_setl_veh_reg_recv_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string c_setl_veh_status
        {
            get
            {
                return this.c_setl_veh_statusField;
            }
            set
            {
                this.c_setl_veh_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string c_setl_date_of_veh_reg
        {
            get
            {
                return this.c_setl_date_of_veh_regField;
            }
            set
            {
                this.c_setl_date_of_veh_regField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string c_setl_keys_recv
        {
            get
            {
                return this.c_setl_keys_recvField;
            }
            set
            {
                this.c_setl_keys_recvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string c_setl_salvage_recv_yn
        {
            get
            {
                return this.c_setl_salvage_recv_ynField;
            }
            set
            {
                this.c_setl_salvage_recv_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string c_setl_salvage_sts
        {
            get
            {
                return this.c_setl_salvage_stsField;
            }
            set
            {
                this.c_setl_salvage_stsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string c_setl_traffic_dept_yn
        {
            get
            {
                return this.c_setl_traffic_dept_ynField;
            }
            set
            {
                this.c_setl_traffic_dept_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string c_setl_clmap_sys_id_in
        {
            get
            {
                return this.c_setl_clmap_sys_id_inField;
            }
            set
            {
                this.c_setl_clmap_sys_id_inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string c_setl_flex_01
        {
            get
            {
                return this.c_setl_flex_01Field;
            }
            set
            {
                this.c_setl_flex_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string c_setl_flex_02
        {
            get
            {
                return this.c_setl_flex_02Field;
            }
            set
            {
                this.c_setl_flex_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string c_setl_flex_03
        {
            get
            {
                return this.c_setl_flex_03Field;
            }
            set
            {
                this.c_setl_flex_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string c_setl_flex_04
        {
            get
            {
                return this.c_setl_flex_04Field;
            }
            set
            {
                this.c_setl_flex_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string c_setl_flex_05
        {
            get
            {
                return this.c_setl_flex_05Field;
            }
            set
            {
                this.c_setl_flex_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string c_setl_flex_06
        {
            get
            {
                return this.c_setl_flex_06Field;
            }
            set
            {
                this.c_setl_flex_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string c_setl_flex_07
        {
            get
            {
                return this.c_setl_flex_07Field;
            }
            set
            {
                this.c_setl_flex_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string c_setl_flex_08
        {
            get
            {
                return this.c_setl_flex_08Field;
            }
            set
            {
                this.c_setl_flex_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string c_setl_flex_09
        {
            get
            {
                return this.c_setl_flex_09Field;
            }
            set
            {
                this.c_setl_flex_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string c_setl_flex_10
        {
            get
            {
                return this.c_setl_flex_10Field;
            }
            set
            {
                this.c_setl_flex_10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string c_setl_flex_11
        {
            get
            {
                return this.c_setl_flex_11Field;
            }
            set
            {
                this.c_setl_flex_11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string c_setl_flex_12
        {
            get
            {
                return this.c_setl_flex_12Field;
            }
            set
            {
                this.c_setl_flex_12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string c_setl_flex_13
        {
            get
            {
                return this.c_setl_flex_13Field;
            }
            set
            {
                this.c_setl_flex_13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string c_setl_flex_14
        {
            get
            {
                return this.c_setl_flex_14Field;
            }
            set
            {
                this.c_setl_flex_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string c_setl_flex_15
        {
            get
            {
                return this.c_setl_flex_15Field;
            }
            set
            {
                this.c_setl_flex_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string c_setl_flex_16
        {
            get
            {
                return this.c_setl_flex_16Field;
            }
            set
            {
                this.c_setl_flex_16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string c_setl_flex_17
        {
            get
            {
                return this.c_setl_flex_17Field;
            }
            set
            {
                this.c_setl_flex_17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string c_setl_flex_18
        {
            get
            {
                return this.c_setl_flex_18Field;
            }
            set
            {
                this.c_setl_flex_18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string c_setl_flex_19
        {
            get
            {
                return this.c_setl_flex_19Field;
            }
            set
            {
                this.c_setl_flex_19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string c_setl_flex_20
        {
            get
            {
                return this.c_setl_flex_20Field;
            }
            set
            {
                this.c_setl_flex_20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string c_setl_flex_21
        {
            get
            {
                return this.c_setl_flex_21Field;
            }
            set
            {
                this.c_setl_flex_21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string c_setl_flex_22
        {
            get
            {
                return this.c_setl_flex_22Field;
            }
            set
            {
                this.c_setl_flex_22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string c_setl_flex_23
        {
            get
            {
                return this.c_setl_flex_23Field;
            }
            set
            {
                this.c_setl_flex_23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string c_setl_flex_24
        {
            get
            {
                return this.c_setl_flex_24Field;
            }
            set
            {
                this.c_setl_flex_24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string c_setl_flex_25
        {
            get
            {
                return this.c_setl_flex_25Field;
            }
            set
            {
                this.c_setl_flex_25Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string c_setl_flex_26
        {
            get
            {
                return this.c_setl_flex_26Field;
            }
            set
            {
                this.c_setl_flex_26Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string c_setl_flex_27
        {
            get
            {
                return this.c_setl_flex_27Field;
            }
            set
            {
                this.c_setl_flex_27Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string c_setl_flex_28
        {
            get
            {
                return this.c_setl_flex_28Field;
            }
            set
            {
                this.c_setl_flex_28Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string c_setl_flex_29
        {
            get
            {
                return this.c_setl_flex_29Field;
            }
            set
            {
                this.c_setl_flex_29Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string c_setl_flex_30
        {
            get
            {
                return this.c_setl_flex_30Field;
            }
            set
            {
                this.c_setl_flex_30Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://settlement.services.insurance.arabia.com/")]
    public partial class settlementCreationRequestInfo
    {
        
        private string c_setl_tran_sys_idField;
        
        private string c_setl_insert_update_flagField;
        
        private string c_setl_clm_sys_idField;
        
        private settlementRequestIn[] c_setl_clm_setl_inField;
        
        private string c_setl_claim_close_ynField;
        
        private string c_setl_close_reason_codeField;
        
        private string c_setl_close_remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string c_setl_tran_sys_id
        {
            get
            {
                return this.c_setl_tran_sys_idField;
            }
            set
            {
                this.c_setl_tran_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string c_setl_insert_update_flag
        {
            get
            {
                return this.c_setl_insert_update_flagField;
            }
            set
            {
                this.c_setl_insert_update_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string c_setl_clm_sys_id
        {
            get
            {
                return this.c_setl_clm_sys_idField;
            }
            set
            {
                this.c_setl_clm_sys_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("settlementDetailsIn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public settlementRequestIn[] c_setl_clm_setl_in
        {
            get
            {
                return this.c_setl_clm_setl_inField;
            }
            set
            {
                this.c_setl_clm_setl_inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string c_setl_claim_close_yn
        {
            get
            {
                return this.c_setl_claim_close_ynField;
            }
            set
            {
                this.c_setl_claim_close_ynField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string c_setl_close_reason_code
        {
            get
            {
                return this.c_setl_close_reason_codeField;
            }
            set
            {
                this.c_setl_close_reason_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string c_setl_close_remarks
        {
            get
            {
                return this.c_setl_close_remarksField;
            }
            set
            {
                this.c_setl_close_remarksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://settlement.services.insurance.arabia.com/", ConfigurationName="PremiaSettlmentProd.SettlementCreationRequestService")]
    public interface SettlementCreationRequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PremiaSettlmentProd.WSExceptionBean), Action="", Name="WSScheduleFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PremiaSettlmentProd.SettlementCreationRequestServiceResponse SettlementCreationRequestService(PremiaSettlmentProd.SettlementCreationRequestService1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PremiaSettlmentProd.SettlementCreationRequestServiceResponse> SettlementCreationRequestServiceAsync(PremiaSettlmentProd.SettlementCreationRequestService1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SettlementCreationRequestService", WrapperNamespace="http://settlement.services.insurance.arabia.com/", IsWrapped=true)]
    public partial class SettlementCreationRequestService1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public PremiaSettlmentProd.settlementCreationRequestInfo SettlementCreationRequestInfo;
        
        public SettlementCreationRequestService1()
        {
        }
        
        public SettlementCreationRequestService1(PremiaSettlmentProd.settlementCreationRequestInfo SettlementCreationRequestInfo)
        {
            this.SettlementCreationRequestInfo = SettlementCreationRequestInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SettlementCreationRequestServiceResponse", WrapperNamespace="http://settlement.services.insurance.arabia.com/", IsWrapped=true)]
    public partial class SettlementCreationRequestServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public PremiaSettlmentProd.settlementCreationResponseInfo SettlementCreationResponse;
        
        public SettlementCreationRequestServiceResponse()
        {
        }
        
        public SettlementCreationRequestServiceResponse(PremiaSettlmentProd.settlementCreationResponseInfo SettlementCreationResponse)
        {
            this.SettlementCreationResponse = SettlementCreationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SettlementCreationRequestServiceChannel : PremiaSettlmentProd.SettlementCreationRequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SettlementCreationRequestServiceClient : System.ServiceModel.ClientBase<PremiaSettlmentProd.SettlementCreationRequestService>, PremiaSettlmentProd.SettlementCreationRequestService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SettlementCreationRequestServiceClient() : 
                base(SettlementCreationRequestServiceClient.GetDefaultBinding(), SettlementCreationRequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SettlementCreationRequestServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SettlementCreationRequestServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SettlementCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), SettlementCreationRequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SettlementCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SettlementCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SettlementCreationRequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SettlementCreationRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SettlementCreationRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PremiaSettlmentProd.SettlementCreationRequestServiceResponse SettlementCreationRequestService(PremiaSettlmentProd.SettlementCreationRequestService1 request)
        {
            return base.Channel.SettlementCreationRequestService(request);
        }
        
        public System.Threading.Tasks.Task<PremiaSettlmentProd.SettlementCreationRequestServiceResponse> SettlementCreationRequestServiceAsync(PremiaSettlmentProd.SettlementCreationRequestService1 request)
        {
            return base.Channel.SettlementCreationRequestServiceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SettlementCreationRequestServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SettlementCreationRequestServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.201.56:8080/ArabiaPolicyClaimWebService/SettlementCreationRequestServic" +
                        "e");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SettlementCreationRequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.SettlementCreationRequestServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SettlementCreationRequestServiceClient.GetEndpointAddress(EndpointConfiguration.SettlementCreationRequestServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            SettlementCreationRequestServicePort,
        }
    }
}
